---
AWSTemplateFormatVersion: '2010-09-09'
EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      KeyName: tutorial
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - InstanceType
          - Arch
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation  
